#floriantschopp/schneith, 07/2019
#!/bin/bash

# Check for arguments
if [ -z "$1" ]; then
  echo "Disable the warnings generated by the protobuf headers by adding pragma's to all header files.";
  echo -e "Usage: disable_warnings.sh CATKIN_DEVEL_SPACE"
  exit -1
fi

DEVEL_SPACE=$1
PROTO_INCLUDES_DIR=$1/include/google/protobuf
TEMPLATE_DIR=$(pwd -P)/template

echo "Attempt to change headers in $PROTO_INCLUDES_DIR"

# Now check if proto headers are installed and the path is correct
if [ ! -d "$PROTO_INCLUDES_DIR" ] || [ ! -f "$PROTO_INCLUDES_DIR/any.h" ]; then
  echo "Could not find eigen headers in the specified devel space!";
  exit -1
fi

# Check wheter the warnings are already disabled
ALREADY_IGNORED=$(cat $PROTO_INCLUDES_DIR/any.h | grep "pragma GCC diagnostic ignored \"-Wunused-parameter\"" | wc -l)
if [ "$ALREADY_IGNORED" -eq "1" ]; then
  echo "Warnings are already disabled, you only need to run this script once!";
  echo "To revert to the original state you can clean and rebuild the protobuf_catkin package.";
  exit -1
fi

# Now recursivly add the header and footer to the headers
find $PROTO_INCLUDES_DIR -name "*.h" -print0 | xargs -0 -I file sh -c "cat $TEMPLATE_DIR/header file $TEMPLATE_DIR/footer > file.new; mv file.new file"
echo "Successfully modified headers to disable the warnings."
echo "To revert to the original state you can clean and rebuild the eigen_catkin package.";
